name-template: 'v$NEXT_PATCH_VERSION 🌈'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - feature
      - enhancement
  - title: '🐛 Bug Fixes'
    labels:
      - bugfix
      - bug
  - title: '🧰 Maintenance'
    labels:
      - chore
      - refactor
  - title: '📚 Documentation'
    labels:
      - documentation
  - title: '🔄 Dependency Updates'
    labels:
      - dependencies
      - dependency
#exclude-labels:
#  - skip-changelog
#  - invalid
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
