#name-template: 'v$NEXT_PATCH_VERSION 🌈'
#tag-template: 'v$NEXT_PATCH_VERSION'
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '⚠️ Breaking Changes'
    labels:
      - breaking-change
      - major
  - title: '🚀 Features'
    labels:
      - feature
      - enhancement
  - title: '🐛 Bug Fixes'
    labels:
      - bugfix
      - bug
  - title: '🧰 Maintenance'
    labels:
      - chore
      - refactor
  - title: '📚 Documentation'
    labels:
      - documentation
      - docs
  - title: '🧪 Tests'
    labels:
      - test
include-labels:
   - breaking-change
   - major
   - feature
   - enhancement
   - bugfix
   - bug
   - chore
   - refactor
   - documentation
   - docs
   - test
exclude-labels:
  - skip-changelog
  - invalid
  - other
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'breaking-change'
      - 'major'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'bugfix'
      - 'bug'
      - 'chore'
      - 'refactor'
      - 'documentation'
      - 'docs'
      - 'test'
  default: patch
template: |
  ## Changes

  $CHANGES
