name: Changelog Check

on:
  pull_request:
      branches:
      - main

jobs:
  check-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Verify Changelog is Modified
        run: |
          if ! git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'CHANGELOG.md'; then
            echo "Error: CHANGELOG.md has not been modified. Please update the Changelog file."
            exit 1
          fi
