name: Changelog Check

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: 'Environment to run tests against'
        type: environment
        required: true
        default: "prod"
      
  pull_request:
      branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate environment and branch
        id: validate
        run: |
          echo "Current Branch: ${GITHUB_REF}"
          CURRENT_BRANCH=$(echo "${GITHUB_REF}" | sed 's|refs/heads/||')
          echo "Current branch2: $CURRENT_BRANCH"
          if [[ "${{ github.event.inputs.ENV }}" == "prod" && "$CURRENT_BRANCH" != "main" ]]; then
            echo "Error: Prod environment can only be deployed from the 'main' branch."
            exit 1
          fi
          echo "Environment and branch validation passed." 
  check-changelog:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code with full history
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Fetch base and head branches
      - name: Fetch branches
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }}

      # Step 3: Check for CHANGELOG.md in changed files
      - name: Verify CHANGELOG.md is Modified
        run: |
          git branch -a
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          HEAD_BRANCH=${{ github.event.pull_request.head.ref }}

          CHANGED_FILES=$(git diff --name-only origin/$BASE_BRANCH...origin/$HEAD_BRANCH)
          echo "Changed files: $CHANGED_FILES"

          if ! echo "$CHANGED_FILES" | grep -q 'CHANGELOG.md'; then
            echo "::error::The file 'CHANGELOG.md' must be updated for this pull request."
            exit 1
          fi
